### ISSUE TITLE
Mobile Search Slider

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#141]
Search bar slides too far to the left on mobile devices. Needs to be a percentage.

**Comment by Le-Roi777** [comment]
Hey @thkruz  whatsup,

I updated the css fixing the issue on my local repo, and I have also added some responsive features to the footer menu.
Let me know where to go from here...i would love to work on some of the other issues and new features : )

**Comment by thkruz** [comment]
![Screenshot_20200816-141216](https://user-images.githubusercontent.com/23319161/90341153-23312580-dfcb-11ea-8e94-3941aac03af6.png)

Still happening. It happened the first time I used the search and then it stopped. Wasn't even able to replicate it when I reloaded.

**Comment by Le-Roi777** [comment]
:confused: ummm let see...I test on 4 different devices including the dev tools devices without any issues.
Where is this happening? Or how can i recreate this screenshot?

**Comment by thkruz** [comment]
Android Pixel 3a in the stock chrome browser. I just cleared the cache to make sure it wasn't pulling an old file. I am going to close it unless it happens again. Thank you again for the better bottom menu setup.
