### ISSUE TITLE
Couple of minor issues

### ISSUE THREAD

**Issue by Le-Roi777** [thkruz/keeptrack.space#157]
### **Fix and update.**

**Top right navigation items response issue in Firefox & Safari.**
- [x] Update css transition.

**Not sure how IE will respond to the application in general.**
- [x] Add IE detection and redirect.

**Brief moments on loading where scrolling is possible.**
- [x] Add new div container to hide all element preventing overflow.

**If there are still issues with this please Re-open.**

**#HTML, #CSS, #JS, #ResponsiveDesign**

**Comment by thkruz** [comment]
Merged. Make sure you open a new branch off the current code or I think it will make me deconflict all the changes I have made since you originally forked it each time...or at least that is what it seemed like.
