### ISSUE TITLE
Optional hints?

### ISSUE THREAD

**Issue by fallensteed** [thkruz/keeptrack.space#190]
Could you program cookies to remember that you've been on the site before so that the hints don't open or a checkbox/popup for opting out of hints on startup?

**Comment by thkruz** [comment]
If you look at https://github.com/thkruz/keeptrack.space/blob/e73605bdaa69f3cbcb43ecc0a5bb5a9538bb3dee/js/advice-module.js#L70 between lines 70 and 87 should do that very thing. My guess is that it wasn't intuitive that pressing the question mark at the top right will disable the help, which is still a problem, but more of a design issue than a code problem.

If you are pressing the question mark and the help is still appearing after you reload the page let me know: What browser, what OS, and are you on keeptrack.space or a local copy of the code.

**Comment by thkruz** [comment]
I think the part that was missing from this bug report was that you downloaded it and ran it offline with the license check disabled haha. In offline mode it was forcing the advice module to turn on - just ran into that myself and updated it to always work regardless of online or offline.
