### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by fallensteed** [thkruz/keeptrack.space#566]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of null (reading 'sccNum')
#### Stack
TypeError: Cannot read properties of null (reading 'sccNum')
    at https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2721:5728
    at Array.sort (<anonymous>)
    at hc (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2721:5695)
    at HTMLDivElement.<anonymous> (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2721:510)

**Comment by thkruz** [comment]
Error is here. Will fix it later.

https://github.com/thkruz/keeptrack.space/blob/6fb804b1c9a3145215a3720a5a0d69f4d98acd74/src/js/plugins/watchlist/watchlist.ts#L528-L554
