### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by vingrirr** [thkruz/keeptrack.space#569]
#### User Description
I selected Lemur 1 and was trying to figure out via Look Angles when it would be in range of the Maui sensor.  I am not sure if this is animated or not.  would be cool to see. 

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'getTime')
#### Stack
TypeError: Cannot read properties of undefined (reading 'getTime')
    at Object.Eo [as cb] (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:1571:2080)
    at https://www.keeptrack.space/js/main.dbe3b4ae7291462593e8.js:2:903301
    at Array.forEach (<anonymous>)
    at Object.selectSatData (https://www.keeptrack.space/js/main.dbe3b4ae7291462593e8.js:2:903287)
    at Object.selectSat (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2721:10890)
    at Va (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2:396269)
    at Object.updateLoop (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2:399827)
    at Ka (https://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2:394649)

**Comment by thkruz** [comment]
Issue appears to be in this section of code:

https://github.com/thkruz/keeptrack.space/blob/e9555bb9a5626dac67a95511952ce544357e3909/src/js/plugins/select-sat-manager/satInfoboxCore.ts#L453-L497

This all deals with the box on the right hand side of the screen when an object is selected. So far it sounds like clicking the lookangles may have been a coincidence. I'll throw an explicit error in for when `sunTime` properties are undefined to help track down what causes this.

Thanks for the report!

**Comment by vingrirr** [comment]
No problem, great work on this stuff.

Is there a way to expose the full Cesium controller to allow us to speed up
or reverse the clock?

**Comment by thkruz** [comment]
Common misconception - this doesn't run on Cesium at all. The engine is entirely custom.

If you click on the time in the top left you can change the time there. If you would like to speed up/slow down the clock then use the + or - keys.

**Comment by vingrirr** [comment]
Really impressive that you did this without Cesium.

I hope all this works out for you and you are super successful at what
you're doing.
However, if things don't work out and you want to work for a large defense
company doing space situational awareness and making similar products to
this, I would be happy to put you in contact with someone.

Thanks for the +/- tip as well!
--Ryan

**Comment by thkruz** [comment]
Issue was caused by updates to my other library Ootk. Ootk.Utils.SunMath.getTimes function now returns more specific time references. dawn, dust, and night were replaced with sunriseStart sunsetEnd and nadir.
