### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by danib2202** [thkruz/keeptrack.space#581]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
e.resize2DMap is not a function
#### Stack
TypeError: e.resize2DMap is not a function
    at HTMLAnchorElement.<anonymous> (http://www.keeptrack.space/js/93.a3245af542dd30d5908b.js:2570:192)

**Comment by thkruz** [comment]
Issue was a leftover reference to uiManager.resize2DMap after resize2DMap was moved out of the uiManager.
