### ISSUE TITLE
Time machine: Year labels not clearing after a while

### ISSUE THREAD

**Issue by RDjarbeng** [thkruz/keeptrack.space#666]
#### Steps to reproduce 
1Open keeptrack.space (https) 
2. Open bottom menu
3. Click night toggle
4. Click time machine 
5. Zoom out as far as possible as satellites increase to be able to see the orbits
6. Wait patiently as time machine runs

#### Current behaviour (bug)
The yellow-green coloured banners showing time machine in year 'x' do not disappear after certain years. They continue to remain on the right side of the screen. Sometimes the issue goes away after I stopp the time machine and reload. 

#### Expected behaviour (correct)
The banners should clear out of the screen after some time.

#### Relevant logs and/or media (optional)
![Screenshot 2023-04-12 154617](https://user-images.githubusercontent.com/57795443/231502125-81a38b6e-cb0e-42bf-80cf-b154e01cdada.png)

```
![image](https://user-images.githubusercontent.com/57795443/231478139-32b5247f-1c5b-41bc-b3bf-8dc17131172c.png)
```

#### Other comment (optional)
Is it also possible to hide the banners in the first place, if I don't want them?

**Comment by thkruz** [comment]
I was able to replicate the problem. The logic is pretty simple for how it makes the toasts, so the only answer I can think of is that the pure volume of orbit lines is causing everything to lag including the async timers that make those go away.

**Comment by thkruz** [comment]
Are you trying to run this on the main website or as a local instance?

I added a toggle to the settings menu to disable the toasts (commit is uploading now, it should be on the live site in the next few days).

**Comment by RDjarbeng** [comment]
Okay, thanks will look forward to it. 
About disabling the toasts however it seems I actually want them there 😅. Because without them the user will not be able to know if the simulation is even progressing or what year they are currently viewing.  It would be cool to have them smaller and out of the way, maybe at the bottom so they don't block the screen. 
Or shorten the text so it takes up less space. For example instead of 'Time machine at year 'X' simply 'Year X' or just "X", where X is year 2019, 2022.

But I guess disabling them is a quick patch.
Thanks for rectifying👌
