### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by dschutt86** [thkruz/keeptrack.space#701]
#### User Description
when clicking on any satellite it kicks it back with this error. 

Otherwise i hope all is well! lets catch up soon!

#### Error Title
TypeError
#### Error Message
Cannot set properties of null (setting 'innerHTML')
#### Stack
TypeError: Cannot set properties of null (setting 'innerHTML')
    at orbitalData (https://interactions.space/forerunner/js/main.js:319270:41)
    at https://interactions.space/forerunner/js/main.js:319201:13

**Comment by dschutt86** [comment]
not sure whats causing it to do this but comes up every time someone clicks on a satellite.

**Comment by thkruz** [comment]
Was caused by an implementation issue with host.
