### ISSUE TITLE
Right Click > Create Sensor Here

### ISSUE THREAD

**Issue by jimsngc** [thkruz/keeptrack.space#772]
#### User Description
Zoomed in and trying to create a custom sensor.  Very new to this software so could well be a n00b user error.

#### Error Title
TypeError
#### Error Message
Cannot read properties of null (reading 'classList')
#### Stack
TypeError: Cannot read properties of null (reading 'classList')
    at Re.rmbMenuActions (https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:1340:63836)
    at HTMLDivElement.<anonymous> (https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:1340:59892)

**Comment by thkruz** [comment]
Definitely not user error. Unfortunately a lot of the code base currently relies on text strings for id fields and I updated one and failed to update it everywhere.

Worse, is that seems to have uncovered a second bug that was introduced a while ago when I added the short term fence menu. I should be able to get this fixed tomorrow after work.

Thank you for reporting it!

**Comment by thkruz** [comment]
Fixed. Merging right now.
