### ISSUE TITLE
Error in Global Error Trapper

### ISSUE THREAD

**Issue by OrginalCarebear** [thkruz/keeptrack.space#775]
#### User Description
Type what you were trying to do here...

#### Error Title
Error
#### Error Message
Satellite position is undefined
#### Stack
snapToSat@https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:708:21391
satCalculate@https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:1340:18510
updateLoop@https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:1340:20008
update_@https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:1444:6690
gameLoop@https://www.keeptrack.space/app/js/main.42ea8abe4075369cdce6.js:1391:15796

**Comment by thkruz** [comment]
Merging with #793.
