### ISSUE TITLE
search-holder DOM missing while trying to update classList

### ISSUE THREAD

**Issue by GMcc13** [thkruz/keeptrack.space#827]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
null is not an object (evaluating '(0,r.G)("search-holder").classList')
#### Stack
searchToggle@https://www.keeptrack.space/app/js/main.37e5299111720ed510c4.js:746:2276959
rmbMenuActions@https://www.keeptrack.space/app/js/main.37e5299111720ed510c4.js:1038:3595504
@https://www.keeptrack.space/app/js/main.37e5299111720ed510c4.js:1038:3588035

**Comment by thkruz** [comment]
Not sure which plugin settings would allow the clear the screen to be visible without the top menu (including search-holder). Can you expand on what you were doing? Any custom settings or specific link you clicked on to launch the app?

I just pushed a fix that will check if the class is there before modifying it, but still curious how you it happened in case I need a smarter check in the plugins loader.

**Comment by thkruz** [comment]
Since you haven't responded and I put a catch in for this error I am going to close this ticket.
