### ISSUE TITLE
TypeError in tleManagerInstance.loadCatalog

### ISSUE THREAD

**Issue by ajmorenom** [thkruz/keeptrack.space#903]
#### User Description
Type what you were trying to do here...

#### Version
9.0.3 - June 25, 2024
#### Error Title
TypeError
#### Error Message
Failed to fetch
#### Stack
TypeError: Failed to fetch

**Comment by thkruz** [comment]
This was caused by an satellite with an argument of perigee that was exactly 360. ootk-core assumed if it was 360 would be passed as 0 in the TLE and barfed. ootk-core has been fixed and KeepTrack was updated to proceed when one TLE fails.
