### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by Waradu** [thkruz/keeptrack.space#911]
#### User Description
I tried clicking this:
![image](https://github.com/user-attachments/assets/445d10d8-b3e4-4186-b711-944044de0e72)

#### Version
10.0.0 - August 15, 2024
#### Error Title
TypeError
#### Error Message
Cannot read properties of null (reading 'period')
#### Stack
TypeError: Cannot read properties of null (reading 'period')
    at a.findObjsByOrbit (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:904:50540)
    at F.nearOrbitsLink_ (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:61:28905)

**Comment by thkruz** [comment]
Really appreciate the screenshot! That button shouldn't be shown on missile objects. It is trying to use the inclination and right ascension to find similar objects. As is, missile objects don't have those parameters, so it throws the error. I might be able to make it work in the future, but for now I will put a patch in tonight to disable the button if it is a missile.

Thanks for the help.

**Comment by thkruz** [comment]
Fixed in 222cef761decbedbbf28b384253da0b307f0ca17
