### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by lahcim** [thkruz/keeptrack.space#960]
#### User Description
Type what you were trying to do here...

#### Version
10.2.0 - October 1, 2024
#### Error Title
TypeError
#### Error Message
Cannot set properties of null (setting 'checked')
#### Stack
TypeError: Cannot set properties of null (setting 'checked')
    at g.syncOnLoad (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:925:2676)
    at ke.keyHandler (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1356:7439)
    at https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1356:5265

**Comment by thkruz** [comment]
Unsure how this happened, but it is easy to mitigate. Added checks before accessing any of the settings-menu elements.
